{% set version = "1.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gh
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gh_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gh/gh_{{ version }}.tar.gz
  sha256: 68c69fcd18429b378e639a09652465a4e92b7b5b5704804d0c5b1ca2b9b58b71

build:
  merge_build_host: true  # [win]
  number: 0

  # This could be noarch -- building everywhere just to test
  #noarch: generic
  # Only building r packages for win64, linux64, osx64
  skip: True # [aarch64 or s390x or ppc64le or arm64]

  rpaths:
    - lib/R/lib/
    - lib/

  # weird error on windows
  missing_dso_whitelist:
    - $RPATH/R.dll  # [win]


requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base {{ r_version }}
    - r-cli >=3.0.1
    - r-gitcreds
    - r-httr2
    - r-ini
    - r-jsonlite
    - r-rlang >=1.0.0
  run:
    - r-base {{ r_version }}
    - r-cli >=3.0.1
    - r-gitcreds
    - r-httr2
    - r-ini
    - r-jsonlite
    - r-rlang >=1.0.0

test:
  commands:
    - $R -e "library('gh')"           # [not win]
    - "\"%R%\" -e \"library('gh')\""  # [win]

about:
  home: https://gh.r-lib.org/, https://github.com/r-lib/gh#readme
  license: MIT
  summary: Minimal client to access the 'GitHub' 'API'.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  skip-lints:
    # These are needed because of bug: https://github.com/anaconda-distribution/anaconda-linter/issues/197
    - http_url
    - invalid_url

    - host_section_needs_exact_pinnings
    - missing_dev_url
    - missing_description
    - missing_documentation

  anaconda-services:
    ref:  https://anaconda.zendesk.com/agent/tickets/35116
    reason: "needed for r-devtools"
    recipe-maintainers:
      - bkreider
      - ianaobi
