{% set version = "1.3.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gh
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gh_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gh/gh_{{ version }}.tar.gz
  sha256: fbaea2abdeceb03d28839fd0e58c2eea01092f9ef92dcc044718ef0d298612ef

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cli >=2.0.1
    - r-gitcreds
    - r-httr >=1.2
    - r-ini
    - r-jsonlite
  run:
    - r-base
    - r-cli >=2.0.1
    - r-gitcreds
    - r-httr >=1.2
    - r-ini
    - r-jsonlite

test:
  commands:
    - $R -e "library('gh')"           # [not win]
    - "\"%R%\" -e \"library('gh')\""  # [win]

about:
  home: https://gh.r-lib.org/, https://github.com/r-lib/gh#readme
  license: MIT
  summary: Minimal client to access the 'GitHub' 'API'.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
