{% set version = "1.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gh
  version: {{ version|replace("-", "_") }}

source:
  fn: gh_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/gh_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gh/gh_{{ version }}.tar.gz
  sha256: 2988440ed2ba4b241c8ffbafbfdad29493574980a9aeba210521dadda91f7eff

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-httr >=1.2
    - r-cli
    - r-ini
    - r-jsonlite
  run:
    - r-base
    - r-httr >=1.2
    - r-cli
    - r-ini
    - r-jsonlite

test:
  commands:
    - $R -e "library('gh')"           # [not win]
    - "\"%R%\" -e \"library('gh')\""  # [win]

about:
  home: https://github.com/r-lib/gh#readme
  license: MIT
  license_file: LICENSE
  summary: Minimal client to access the 'GitHub' 'API'.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
