travis:
  secure:
    BINSTAR_TOKEN: DaTU1rxVBFVU+QI6nEiTHqgD2UA+4DLKNqhV1HPFI288/J9tOdf0cYmZEw9Fln6SktYUxVqtdD4o6+b7LUzmqWmO+iVIbjtPYpSOBwvN14vcDAObWn5kfcY3+GdJWHCiScoHtvjzIwG9Z/tts+hSdzyqvnnBcExCYB9LXdAjGDJX566aj9cVWeSJXIyqlTrK0Ze+IDf7M680+uOW6HYhtXKrjqtjQoYBy6L6cZhyMRJUyA6fesSSl+DhVy+o37AfB7drVF4n9VW99SbZ8kz/aqD1zjIqIImiRXUMqpgK+clVTLx59Gr8kfs6JqqN96AA6naxIuoW7vKFIpu4/zHe6zx08Hpdf8dPhODbuRE9Jpbe9P+Jbxqq7DWiDLdWsA3JpS6f7JbJzOwxac3/FTnQJcNxQ19czUzT/R/yYAPN8qvQwcUdm6kPJzK2pn52h1vu67D8Ha0yHxkVZZEgno5AL7uBYsPo6Sck/2vVLLI3xgY2Sg6e8VCgfETGgFiu9ao3s+0X5dJ7M387jSf2NmwOK37i2Hp0HFnLt9juMcP4qak/MXEpQ0ea2F0oIsR2RMNPc73+mmCtr13pz9/29asQLoTXCMjyoNNo1SHujKfmVuzlFazJc3RuQHTmQ4O8pzlhcWvTcjWWTpTAaeLjR39m/NvqJoBFXyUMAtN51rQYCHU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
