appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: qCd6ShXgcwpcy0pMIeDciK6PU0uTCz9cRoi93StmEmqDzyYAvhpbAfF+ScsG0dk1wsFxxolRP4Mb5OpEPzgexhUdIM8yztepoEMKr4nl7CDE5VRxHh5yBCW1pG50iJCiX6JQHAZ3JDRY86+xBLAOSYqt9V+mBGpdEuWTj0ETab6aijA3k8W8BOb+50cFTBYuR0hjzq6aYNo86BRHKA9IaGcMG0lP/gfY8lIQdGq8yFfFdqYoX4aFmzXJWMlGZF5pSwyPa+1gZXeDKV9PU1sWUgLv0SxMd5UVQhYCLs7X3H8gT+QuA/tR/PvQPQWBiLlH1Sq7jGuhg2WoZf2YZuLe3n+y+nKNU3SVSaS3FUL58JQbyraArou8VWl775xKZnX2SYxQY+SwNQ52IZFfLNkI7fWrl4Ar12n6SVCHkHfxNa7GJ9838ImDtG1dqzeNRujqlGUXpOUU0mRz8TU+3IhARmeFxBbVOw2wTtYm4yWkpBEvrS1rzVHiaWowNUJMjhiSZRqFOWWt2T4bYiVypE68uL9akS3vkllYdFGEy8Nj74oPXXWBU8Uf0rKcajrTKrrQQp6yiY4clIgViM6i7SucYVtmWr6/UGxIALyyLeK8lYlsln9YAZStmfWYJV/pyLE/XWeDSDxo9Gd4daL/zTPzN5J++DHa6zNt7vlYYpE5RCc=}
bot:
  automerge: true
